/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ww_fh_efd_an1_MainActivity_show_camera */

#ifndef _Included_com_ww_fh_efd_an1_MainActivity_show_camera
#define _Included_com_ww_fh_efd_an1_MainActivity_show_camera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ww_fh_efd_an1_MainActivity_show_camera
 * Method:    efdSetStorageRoot
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ww_fh_efd_1an1_MainActivity_1show_1camera_efdSetStorageRoot
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ww_fh_efd_an1_MainActivity_show_camera
 * Method:    efdHelloTest
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ww_fh_efd_1an1_MainActivity_1show_1camera_efdHelloTest
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ww_fh_efd_an1_MainActivity_show_camera
 * Method:    efdHelloTest0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ww_fh_efd_1an1_MainActivity_1show_1camera_efdHelloTest0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ww_fh_efd_an1_MainActivity_show_camera
 * Method:    efdInitSystem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ww_fh_efd_1an1_MainActivity_1show_1camera_efdInitSystem
  (JNIEnv *, jobject);

/*
 * Class:     com_ww_fh_efd_an1_MainActivity_show_camera
 * Method:    efdSnapShotCalibrate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ww_fh_efd_1an1_MainActivity_1show_1camera_efdSnapShotCalibrate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ww_fh_efd_an1_MainActivity_show_camera
 * Method:    efdSnapShotAnalyze
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ww_fh_efd_1an1_MainActivity_1show_1camera_efdSnapShotAnalyze
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ww_fh_efd_an1_MainActivity_show_camera
 * Method:    efdSnapShotAnalyzeMM
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ww_fh_efd_1an1_MainActivity_1show_1camera_efdSnapShotAnalyzeMM
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ww_fh_efd_an1_MainActivity_show_camera
 * Method:    efdNextNewBatch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ww_fh_efd_1an1_MainActivity_1show_1camera_efdNextNewBatch
  (JNIEnv *, jobject);

/*
 * Class:     com_ww_fh_efd_an1_MainActivity_show_camera
 * Method:    efdPrevOldNBatch
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ww_fh_efd_1an1_MainActivity_1show_1camera_efdPrevOldNBatch
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ww_fh_efd_an1_MainActivity_show_camera
 * Method:    efdReviewMarkupImg
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ww_fh_efd_1an1_MainActivity_1show_1camera_efdReviewMarkupImg
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ww_fh_efd_an1_MainActivity_show_camera
 * Method:    efdReviewImg
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ww_fh_efd_1an1_MainActivity_1show_1camera_efdReviewImg
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ww_fh_efd_an1_MainActivity_show_camera
 * Method:    efdGetSampleCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ww_fh_efd_1an1_MainActivity_1show_1camera_efdGetSampleCount
  (JNIEnv *, jobject);

/*
 * Class:     com_ww_fh_efd_an1_MainActivity_show_camera
 * Method:    efdSelectScopeProfile
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ww_fh_efd_1an1_MainActivity_1show_1camera_efdSelectScopeProfile
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ww_fh_efd_an1_MainActivity_show_camera
 * Method:    efdSelectFiberProfile
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ww_fh_efd_1an1_MainActivity_1show_1camera_efdSelectFiberProfile
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
